### ISSUE TITLE
nio patch in main section causes exception with java7 application

### ISSUE THREAD

**Issue by rleitner** [woglinde/meta-java#60]
Commit 83096c2ebba8e17cde48058931caa1211fa8c080 made jre7 throw an exception when starting my application.
My machine is an ARMv7 and I'm using openjdk-7-jre "25b30-2.3.12".
When I revert the commit everything is working fine.

The exception is listed below:
```
Exception in thread "Application" 2014-04-23 11:54:25,329 Application     Exception in thread "Application" 
java.lang.reflect.InvocationTargetException2014-04-23 11:54:25,333 Application     java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)2014-04-23 11:54:25,334 Application            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)2014-04-23 11:54:25,336 Application          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)2014-04-23 11:54:25,337 Application          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)2014-04-23 11:54:25,338 Application       at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)2014-04-23 11:54:25,339 Application          at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)2014-04-23 11:54:25,340 Application         at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.awt.AWTError: Toolkit not found: sun.awt.X11.XToolkit2014-04-23 11:54:25,342 Application     Caused by: java.awt.AWTError: Toolkit not found: sun.awt.X11.XToolkit
        at java.awt.Toolkit$2.run(Toolkit.java:875)2014-04-23 11:54:25,343 Application       at java.awt.Toolkit$2.run(Toolkit.java:875)
        at java.security.AccessController.doPrivileged(Native Method)2014-04-23 11:54:25,344 Application             at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:860)2014-04-23 11:54:25,345 Application           at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:860)
        at com.mine.Application.main(Application.java:206)2014-04-23 11:54:25,346 Application            at com.mine.Application.main(Application.java:206)
        ... 6 more2014-04-23 11:54:25,347 Application        ... 6 more
```

I'll open a Pull-Request for reverting the commit 83096c2ebba8e17cde48058931caa1211fa8c080.
Please check if this is the "best" solution.

regards,
Richard

**Comment by woglinde** [comment]
meta-java has moved you can find it now under

git://git.yoctoproject.org/meta-java
