### ISSUE TITLE
No X11 support for openjdk-7-jre

### ISSUE THREAD

**Issue by ronaldonunez** [woglinde/meta-java#71]
I was trying to run a graphical application in a iMX6 board through an image built using Yocto 1.6. I got the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-7-openjdk/jre/lib/arm/xawt/libmawt.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1842)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1061)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1953)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1878)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1087)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1646)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
	at java.awt.Insets.<clinit>(Insets.java:89)
	at javax.swing.plaf.synth.SynthLookAndFeel.<clinit>(SynthLookAndFeel.java:70)
	at br.com.ronaldonunez.presd.Main.main(Main.java:33)
```

Any help? Thanks in advance.

**Comment by johnkajava** [comment]
Even i got the same error

<a href="http://wisentechnologies.com/it-courses/java-training.aspx" title="Java Training in Chennai">Java Training  in Chennai</a>

**Comment by woglinde** [comment]
Hi,

meta-java has moved, you can now find it under

git://git.yoctoproject.org/meta-java

and it have now the option to build without x11.
